### ISSUE TITLE
Wrong configuration for proxy

### ISSUE THREAD

**Issue by ktibi** [lrk/ansible-role-sonarqube#14]
Hi,

When I configure proxy I have that : 

```
# UPDATE CENTER

sonar.updatecenter.activate=true
http.proxyHost=localhosthttp.proxyPort=3128
```
Maybe need to add new line for second param.

**Comment by lrk** [comment]
@ktibi thank you for pointing that out !

**Comment by ktibi** [comment]
Thank for your role ;)

I'll make PR soon for add ldap support.

**Comment by lrk** [comment]
Fixed
